# Uncomment this line to define a global platform for your project

platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

target "BodiTrak" do

pod 'SystemServices'
pod 'AFNetworking', '~> 3.0'
pod 'PureLayout'
pod 'EventSource'
pod 'CorePlot'
end
